LOG_DIR = "logs"
LOG_FILE = "posts.log"
MAX_BYTES = 5 * 1024 * 1024
BACKUP_COUNT = 5

DATABASE_DIR = "database"
DATABASE_NAME = "posts.db"

JWT_SECRET_KEY = "your-secret-key"
JWT_ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 15
REFRESH_TOKEN_EXPIRE_HOURS = 24
SALT_LENGTH = 12
